SELECT  A.AUTHOR_ID, A.AUTHOR_NAME, 
        CATEGORY, SUM(C.SALES * B.PRICE) TOTAL_SALES
FROM AUTHOR A
    JOIN BOOK B
    ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN BOOK_SALES C
    ON B.BOOK_ID = C.BOOK_ID
 WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY 1, 3
ORDER BY 1, 3 DESC;
