SELECT TG.ID
FROM ECOLI_DATA FG
LEFT JOIN ECOLI_DATA SG
    ON FG.ID = SG.PARENT_ID
LEFT JOIN ECOLI_DATA TG
    ON SG.ID = TG.PARENT_ID 
WHERE   FG.PARENT_ID IS NULL 
    AND TG.PARENT_ID IS NOT NULL
ORDER BY TG.ID;