
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO A 
WHERE (FOOD_TYPE, FAVORITES) IN
(
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY 1
)
ORDER BY 1 DESC;