SELECT  A.REST_ID AS REST_ID,
        A.REST_NAME AS REST_NAME,
        A.FOOD_TYPE AS FOOD_TYPE,
        A.FAVORITES AS FAVORITES,
        A.ADDRESS AS ADDERESS,
        ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A
JOIN REST_REVIEW B
ON A.REST_ID = B.REST_ID
WHERE LEFT(A.ADDRESS, 2) = "서울"
GROUP BY REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDERESS
ORDER BY SCORE DESC, A.FAVORITES DESC
;