SELECT  YEAR(SALES_DATE) YEAR,
        MONTH(SALES_DATE) MONTH,
        B.GENDER,
        COUNT(DISTINCT A.USER_ID) USERS
FROM ONLINE_SALE A
JOIN USER_INFO B
ON A.USER_ID = B.USER_ID
WHERE B.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
