WITH JOINED_2021 AS
(
    SELECT COUNT(DISTINCT USER_ID) TOTAL_COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) 
SELECT  YEAR(sales_date) YEAR,
        MONTH(sales_date) MONTH,
        COUNT(DISTINCT A.USER_ID) PURCHASED_USERS, 
        ROUND((COUNT(DISTINCT(A.USER_ID)) / (SELECT TOTAL_COUNT FROM JOINED_2021)),1) PUCHASED_RATIO
FROM ONLINE_SALE A
JOIN USER_INFO B
    ON A.USER_ID = B.USER_ID
WHERE YEAR(B.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;