WITH RECURSIVE HOURS 
    AS
    (
        SELECT 0 HOUR

        UNION ALL

        SELECT HOUR + 1
        FROM HOURS
        WHERE HOUR < 23
    )
SELECT A.HOUR HOUR, COUNT(ANIMAL_ID) COUNT
FROM HOURS A
LEFT JOIN ANIMAL_OUTS B
ON A.HOUR = HOUR(B.DATETIME)
GROUP BY HOUR
ORDER BY HOUR
