-- JOIN
SELECT  
    DISTINCT ID, 
    EMAIL, 
    FIRST_NAME, 
    LAST_NAME
FROM DEVELOPERS D
    JOIN SKILLCODES S
    ON S.NAME IN ("C#", "Python")
    AND D.SKILL_CODE & S.CODE  = S.CODE
ORDER BY ID;

-- INNER QUERY

-- SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
-- FROM DEVELOPERS
-- WHERE SKILL_CODE & (SELECT SUM(code) FROM skillcodes WHERE name IN ('C#', 'Python'))
-- ORDER BY ID;
