

SELECT YEAR(DIFFERENTIATION_DATE) AS "YEAR",
        (MAX_SIZE - SIZE_OF_COLONY) AS "YEAR_DEV",
        ID
FROM ECOLI_DATA A
JOIN (
        SELECT YEAR(DIFFERENTIATION_DATE) "YEARS", MAX(SIZE_OF_COLONY) "MAX_SIZE"
        FROM ECOLI_DATA
        GROUP BY YEARS
     ) B
ON YEAR(DIFFERENTIATION_DATE) = B.YEARS
ORDER BY 1, 2
