WITH CAR AS
(
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
)
SELECT DISTINCT(CAR.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR 
        ON CAR.CAR_ID = H.CAR_ID
WHERE MONTH(START_DATE) = 10
ORDER BY CAR.CAR_ID DESC;
